In [1]:
import numpy as np

In [54]:
a = np.array([(1, 2, 3, 3, 1), (6, 8, 11, 10, 7)])
print(a)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [120]:
mean_a = a.mean(axis=1, keepdims = True)
print(mean_a)

[[2. ]
 [8.4]]


In [121]:
a_centered = a -  mean_a
print(a_centered)

[[-1.   0.   1.   1.  -1. ]
 [-2.4 -0.4  2.6  1.6 -1.4]]


In [134]:
a_centered_sp = np.dot(a_centered, 2)
a_centered_sp

array([[-2. ,  0. ,  2. ,  2. , -2. ],
       [-4.8, -0.8,  5.2,  3.2, -2.8]])

In [136]:
###Задание 3 не нашел способа найти скалярное произведенеи###



In [138]:
import pandas as pd

In [139]:
authors = pd.DataFrame({'author_id' : [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [141]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3], 
                     'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]})

book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [143]:
authors_price = pd.merge(authors, book)
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [157]:
top5 = pd.DataFrame(authors_price.sort_values('price', ascending = False))
top5.head(5)

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [175]:
authors_stat = authors_price.describe()
authors_stat

author_id       price
count   7.000000    7.000000
mean    1.857143  387.142857
std     0.899735   80.976187
min     1.000000  290.000000
25%     1.000000  325.000000
50%     2.000000  370.000000
75%     2.500000  450.000000
max     3.000000  500.000000